#Residence.destroy_all
Administrator.destroy_all


Residence.find_or_create_by(nombre: "Albar Club de Mar", descripcion: "El complejo Building Albar tiene dos espacios diferentes: un área gastronómica abierta a todo el público y un área de recreación privada con piscinas, decks y solárium. Tiene cocheras con portón automatizado con comando a distancia. Ademas cuentan con sauna, hidromasaje, piscina climatizada, área de fitness y vestuarios con acceso independiente. El complejo brinda todo en cuanto a tecnología, confort, seguridad y un diseño moderno en armonía con el entorno.", urlImag: "https://www.rci.com/static/Resorts/Assets/D448E01L.jpg",precio:20000, pais: "Argentina", provincia: "Buenos Aires", localidad: "Pinamar", direccion: "Av. Jorge Bunge, entre Jason y Av. Intermédanos, #D448.")
Residence.find_or_create_by(nombre: "Aldea Andina", descripcion: "Los servicios de Aldea Andina incluyen Wi-Fi en todo el recinto, zonas comunes y privadas, piscina climatizada interior y exterior, servicios de SPA, cancha de tenis, un quincho para asados, un fogón, lugar de juegos de mesa y un parque de juegos para los niños en el fabuloso parque de cuatro acres rodeado de una gran variedad de árboles.", urlImag: "https://www.rci.com/static/Resorts/Assets/1940E02L.jpg",precio: 18000, pais: "Argentina", provincia: "Río Negro", localidad: "San Carlos de Bariloche", direccion: "Av. Pioneros, #1949")
Residence.find_or_create_by(nombre: "Club Cariló Playa", descripcion: "El complejo cuenta con un clubhouse, una sala para leer, un solarium, piscina exterior y cubierta, gimnasio, sauna, acceso directo a la playa y WI-FI. El condominio está formado por 4 edificios con departamentos de 1, 2 y 3 ambientes totalmente equipados con parrillas y balcones individuales. Dichos departamentos tienen una capacidad de 2 a 7 personas, con vista al mar y al bosque. Desarrollados en un amplio parque con salida exclusiva a la playa", urlImag: "https://www.rci.com/static/Resorts/Assets/2909E01L.jpg",precio:20000 , pais: "Argentina", provincia: "Buenos Aires", localidad: "Cariló", direccion: "Av. Avutarda, #2909")
Residence.find_or_create_by(nombre: "Howard Johnson la Canada & Suites", descripcion: " Este centro cultural y comercial se encuentra en las estribaciones de las montañas de Sierra Chica en el río Suquia. Es una ciudad moderna, a pesar de sus muchos edificios que datan de la época colonial. Córdoba combina la actividad urbana e industrial con la relajación. Situado junto a las sierras y lagos, es ideal para turistas que buscan tranquilidad y belleza en el entorno. Los valles de Córdoba invitan a ser explorados. Su ubicación también ofrece una zona ideal para practicar deportes de aventura", urlImag: "https://www.rci.com/static/Resorts/Assets/C528E01L.jpg",precio: 400000, pais: "Argentina", provincia: "Córdoba", localidad: "CBA", direccion: "Av. Figueroa Alcorta y Colon, #C528")
Residence.find_or_create_by(nombre: "Le Mirage Village Club", descripcion: "Está situado en la colina con vistas a las Sierras Chicas. A sólo 5 minutos de la villa y a 25 de la ciudad de Córdoba, tiene 36 apartamentos (para 2, 3, 4, 5, 6 y 7 personas). El centro vacacional cuenta con un restaurante y confitería, servicio de habitaciones, parrilleras de usos múltiples, piscinas climatizadas al aire libre, servicio de limpieza y cambio de ropa, vigilancia nocturna, hidromasaje para grupos de hasta 4 personas y actividades recreativas programadas", urlImag: "https://www.rci.com/static/Resorts/Assets/6482E01L.jpg",precio:32000 , pais: "Argentina", provincia: "Córdoba", localidad: "Villa Carlos Paz", direccion: "Directorio, #6482 ")
Residence.find_or_create_by(nombre: "Apartur Las Leñas", descripcion: "Ubicado en el Valle de Las Leñas, Super Resort ofrece amplios apartamentos completamente equipados con interiores de madera, balcones con vistas a la montaña, cocina, zona de comedor, calefacción y capacidad para hasta 6 personas. El Resort cuenta con un lobby con servicio gratuito de Wi-Fi, un bar y un restaurant. Además de esquiar, los huéspedes podrán practicar rafting, equitación y senderismo. También se organizan actividades al aire libre durante todo el año. Se ofrece un servicio de transporte gratuito desde / hacia el Aeropuerto de Malargüe, situado a 58 km. El transporte en bus dentro del Valle de las Leñas es gratuito.", urlImag: "https://www.rci.com/static/Resorts/Assets/D931E01L.jpg",precio:20000, pais: "Argentina", provincia: "Mendoza", localidad: "Las leñas", direccion: "Malargue,	#5612")
Residence.find_or_create_by(nombre: "Campo Las Tinajas", descripcion: "Hay una piscina, piscina para niños y parque infantil.", urlImag: "https://www.rci.com/static/Resorts/Assets/R647E01L.jpg",precio:30000, pais: "Argentina", provincia: "San Luis", localidad: "Merlo", direccion: "Av. Dos venados, #647")
Residence.find_or_create_by(nombre: "Australis Paradise", descripcion: "El complejo de 4 estrellas superior es rodeado de un inmenso bosque y cuenta con 38 apartamentos Studio, Cabañas y Dúplex con vista a la piscina central. Se ubica a media cuadra del centro comercial y tres cuadras del mar. -Desayuno continental buffet -Estacionamiento descubierto - Piscina climatizada cubierta. - Piscina para adultos y niños descubierta (en temporada alta). - Sauna. - Duchas escocesas. - Gimnasio con aparatos. - Tratamientos de Spa - Actividades recreativas (fines de semana largo y temporada alta). - Club de Mar frente al hotel con sillas y sombrillas en la playa (en temporada alta) - Room service*. - Wi-fi libre. - Servicio telefónico y acceso a Internet. - Servicio de lavandería. - Baby sitter - Cabalgatas. - Cuatriciclos. - 4 x 4. ", urlImag: "https://www.rci.com/static/Resorts/Assets/R967E01L.jpg",precio:15000, pais: "Argentina", provincia: "Buenos Aires", localidad: "Cariló", direccion: "Boyero e/ Arrayán y Aromo, #647")
Residence.find_or_create_by(nombre: "Australis Yene Hue", descripcion: "Un hotel superior de 4 estrellas, situado estratégicamente en la ciudad frente al mar y a minutos de la península de Valdés, se encuentra Australis Yene hue, 'lugar de las ballenas' en el idioma mapuche. Está construido sobre una superficie de 1000 m2 y cuenta con 11 pisos para favorecer las mejores vistas, 71 habitaciones, un spa completo, un restaurante temático de tango y salones para convenciones. Este hotel ofrece el enfoque más sofisticado para este destino. El hotel dispone de una piscina interior climatizada, servicio de spa y desayuno continental. También hay un restaurante y un bar en el hotel. ", urlImag: "https://www.rci.com/static/Resorts/Assets/A354E01L.jpg",precio:16000, pais: "Argentina", provincia: "Chubut", localidad: "Puerto Madryn", direccion: "Av. Julio Argentino Roca  e Hipólito Yrigoyen, #354")
Residence.find_or_create_by(nombre: "Cabañas 'Ayelen Andina'", descripcion: "El desarrollo cuenta con un Club House de 400m2, salón comedor, Business Center y gimnasio moderno. ofrece chalés con cocina, balcón, chimenea y calefacción. Cuenta con un mostrador de información turística, un bar y conexión Wi-Fi gratuita. También, hay aparcamiento gratuito. Las 16 cabañas son para 4, 6 u 8 personas de 1, 2 o 3 dormitorios y con 1 o 2 baños.", urlImag:"https://www.rci.com/static/Resorts/Assets/R510E02L.jpg", precio:18000, pais: "Argentina", provincia: "Chubut", localidad: "Esquel", direccion: "Chubut e/ S. Luis y la pampa, #510")
Residence.find_or_create_by(nombre: "Bauen Suite Hotel", descripcion: "Suites con sala de estar y cocina americana divididas. Computadoras para uso de los huéspedes. Bufé para desayuno. Restaurante y bar con cocina internacional. Servicio de habitaciones. Patio para café. Servicio de lavandería y tintorería. Masaje con cita. Servicio de transporte. Estacionamiento pago. Sala de reuniones con Internet y la posibilidad de servicios de secretarias, traductores, fax, alquiler de portátil y más. 2 salas de eventos. ", urlImag:"https://www.rci.com/static/Resorts/Assets/1275E01L.jpg", precio:20000, pais: "Argentina", provincia: "Buenos Aires", localidad: "Bs As", direccion: "Av. Corrientes e/ Callao y Riobamba")
Residence.find_or_create_by(nombre: "Bahía Manzano", descripcion: "Unidades con vista al lago. Limpieza diaria. Piscina climatizada y solárium (octubre a abril). Costa de lago con playa. Fitness center: Gym, sauna y ducha escocesa. Masajes (con costo adicional). Play room. Rinconcito Infantil (niños 3 a 5 años que no usen pañales). Sector deportivo (época estival) con cancha de tenis, futbol, paddle, voley, juegos de plaza para niños. Actividades recreativas para todas las edades. Wi fi, caja de seguridad en la unidad, estacionamiento. Restaurant. Club House & Bar. Servicio de lavado de vajilla (costo adicional). Servicio de lavandería (costo adicional). Recepción 24 hs.", urlImag:"https://www.rci.com/static/Resorts/Assets/6796E01L.jpg",precio:22000, pais: "Argentina", provincia: "Neuquén", localidad: "Villa La Angostura", direccion: "Osa Mayor, e/ Cabellera de la Berenice y Antares")





# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

